const DEFAULT_CARDS = [
{id:'C1',num:'1',name:'MESSI',team:'Argentina',cc:'ARG',type:'LIMITED'},
{id:'C2',num:'2',name:'VINÍCIUS JÚNIOR',team:'Brazil',cc:'BRA',type:'LIMITED'},
{id:'C3',num:'3',name:'SALAH',team:'Egypt',cc:'EGY',type:'LIMITED'},
{id:'C4',num:'4',name:'KANE',team:'England',cc:'ENG',type:'LIMITED'},
{id:'C5',num:'5',name:'MBAPPÉ',team:'France',cc:'FRA',type:'LIMITED'},
{id:'C6',num:'6',name:'SON',team:'Korea Republic',cc:'KOR',type:'LIMITED'},
{id:'C7',num:'7',name:'HAALAND',team:'Norway',cc:'NOR',type:'LIMITED'},
{id:'C8',num:'8',name:'RONALDO',team:'Portugal',cc:'POR',type:'LIMITED'},
{id:'C9',num:'9',name:'YAMAL',team:'Spain',cc:'ESP',type:'LIMITED'},
{id:'C10',num:'10',name:'RAYAN AÏT-NOURI',team:'Algeria',cc:'ALG',type:'HERO'},
{id:'C11',num:'11',name:'TEAM CREST',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C12',num:'12',name:'RIYAD MAHREZ',team:'Algeria',cc:'ALG',type:'ICON'},
{id:'C13',num:'13',name:'ALEXIS GUENDOUZ',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C14',num:'14',name:'RAMY BENSEBAINI',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C15',num:'15',name:'YOUCEF ATAL',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C16',num:'16',name:'AÏSSA MANDI',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C17',num:'17',name:'NABIL BENTALEB',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C18',num:'18',name:'SAÏD BENRAHMA',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C19',num:'19',name:'AMINE GOUIRI',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C20',num:'20',name:'MOHAMED AMOURA',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C21',num:'21',name:'BAGHDAD BOUNEDJAH',team:'Algeria',cc:'ALG',type:'BASE'},
{id:'C22',num:'22',name:'JULIÁN ÁLVAREZ',team:'Argentina',cc:'ARG',type:'HERO'},
{id:'C23',num:'23',name:'TEAM CREST',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C24',num:'24',name:'LIONEL MESSI',team:'Argentina',cc:'ARG',type:'ICON'},
{id:'C25',num:'25',name:'EMILIANO MARTÍNEZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C26',num:'26',name:'NAHUEL MOLINA',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C27',num:'27',name:'CRISTIAN ROMERO',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C28',num:'28',name:'NICOLÁS OTAMENDI',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C29',num:'29',name:'ENZO FERNÁNDEZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C30',num:'30',name:'ALEXIS MAC ALLISTER',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C31',num:'31',name:'RODRIGO DE PAUL',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C32',num:'32',name:'GIULIANO SIMEONE',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C33',num:'33',name:'LAUTARO MARTÍNEZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C34',num:'34',name:'HARRY SOUTTAR',team:'Australia',cc:'AUS',type:'HERO'},
{id:'C35',num:'35',name:'TEAM CREST',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C36',num:'36',name:'MATHEW RYAN',team:'Australia',cc:'AUS',type:'ICON'},
{id:'C37',num:'37',name:'ALESSANDRO CIRCATI',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C38',num:'38',name:'JORDAN BOS',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C39',num:'39',name:'LEWIS MILLER',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C40',num:'40',name:'MILOS DEGENEK',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C41',num:'41',name:'JACKSON IRVINE',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C42',num:'42',name:'RILEY MCGREE',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C43',num:'43',name:'AIDEN O\'NEILL',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C44',num:'44',name:'CONNOR METCALFE',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C45',num:'45',name:'CRAIG GOODWIN',team:'Australia',cc:'AUS',type:'BASE'},
{id:'C46',num:'46',name:'MARKO ARNAUTOVIĆ',team:'Austria',cc:'AUT',type:'HERO'},
{id:'C47',num:'47',name:'TEAM CREST',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C48',num:'48',name:'DAVID ALABA',team:'Austria',cc:'AUT',type:'ICON'},
{id:'C49',num:'49',name:'ALEXANDER SCHLAGER',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C50',num:'50',name:'KEVIN DANSO',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C51',num:'51',name:'PHILIPP LIENHART',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C52',num:'52',name:'KONRAD LAIMER',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C53',num:'53',name:'NICOLAS SEIWALD',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C54',num:'54',name:'MARCEL SABITZER',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C55',num:'55',name:'FLORIAN GRILLITSCH',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C56',num:'56',name:'CHRISTOPH BAUMGARTNER',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C57',num:'57',name:'MICHAEL GREGORITSCH',team:'Austria',cc:'AUT',type:'BASE'},
{id:'C58',num:'58',name:'YOURI TIELEMANS',team:'Belgium',cc:'BEL',type:'HERO'},
{id:'C59',num:'59',name:'TEAM CREST',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C60',num:'60',name:'KEVIN DE BRUYNE',team:'Belgium',cc:'BEL',type:'ICON'},
{id:'C61',num:'61',name:'THIBAUT COURTOIS',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C62',num:'62',name:'ARTHUR THEATE',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C63',num:'63',name:'TIMOTHY CASTAGNE',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C64',num:'64',name:'MAXIM DE CUYPER',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C65',num:'65',name:'AMADOU ONANA',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C66',num:'66',name:'JÉRÉMY DOKU',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C67',num:'67',name:'CHARLES DE KETELAERE',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C68',num:'68',name:'LEANDRO TROSSARD',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C69',num:'69',name:'ROMELU LUKAKU',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C70',num:'70',name:'MARQUINHOS',team:'Brazil',cc:'BRA',type:'HERO'},
{id:'C71',num:'71',name:'TEAM CREST',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C72',num:'72',name:'VINÍCIUS JÚNIOR',team:'Brazil',cc:'BRA',type:'ICON'},
{id:'C73',num:'73',name:'ALISSON',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C74',num:'74',name:'DANILO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C75',num:'75',name:'ÉDER MILITÃO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C76',num:'76',name:'GABRIEL MAGALHÃES',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C77',num:'77',name:'CASEMIRO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C78',num:'78',name:'BRUNO GUIMARÃES',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C79',num:'79',name:'RODRYGO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C80',num:'80',name:'MATHEUS CUNHA',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C81',num:'81',name:'RAPHINHA',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C82',num:'82',name:'JONATHAN DAVID',team:'Canada',cc:'CAN',type:'HERO'},
{id:'C83',num:'83',name:'TEAM CREST',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C84',num:'84',name:'ALPHONSO DAVIES',team:'Canada',cc:'CAN',type:'ICON'},
{id:'C85',num:'85',name:'DAYNE ST. CLAIR',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C86',num:'86',name:'RICHIE LARVEA',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C87',num:'87',name:'DEREK CORNELIUS',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C88',num:'88',name:'STEPHEN EUSTÁQUIO',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C89',num:'89',name:'ISMAËL KONÉ',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C90',num:'90',name:'JONATHAN OSORIO',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C91',num:'91',name:'JACOB SHAFFELBURG',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C92',num:'92',name:'TAJON BUCHANAN',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C93',num:'93',name:'CYLE LARIN',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C94',num:'94',name:'VOZINHA',team:'Cape Verde',cc:'CPV',type:'HERO'},
{id:'C95',num:'95',name:'TEAM CREST',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C96',num:'96',name:'RYAN MENDES',team:'Cape Verde',cc:'CPV',type:'ICON'},
{id:'C97',num:'97',name:'LOGAN COSTA',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C98',num:'98',name:'PICO',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C99',num:'99',name:'STEVEN MOREIRA',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C100',num:'100',name:'JOÃO PAULO',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C101',num:'101',name:'KEVIN PINA',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C102',num:'102',name:'JAMIRO MONTEIRO',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C103',num:'103',name:'YANNICK SEMEDO',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C104',num:'104',name:'JOVANE CABRAL',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C105',num:'105',name:'DAILON LIVRAMENTO',team:'Cape Verde',cc:'CPV',type:'BASE'},
{id:'C106',num:'106',name:'LUIS DÍAZ',team:'Colombia',cc:'COL',type:'HERO'},
{id:'C107',num:'107',name:'TEAM CREST',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C108',num:'108',name:'JAMES RODRÍGUEZ',team:'Colombia',cc:'COL',type:'ICON'},
{id:'C109',num:'109',name:'CAMILO VARGAS',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C110',num:'110',name:'DÁVINSON SÁNCHEZ',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C111',num:'111',name:'YERRY MINA',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C112',num:'112',name:'DANIEL MUÑOZ',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C113',num:'113',name:'JEFFERSON LERMA',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C114',num:'114',name:'RICHARD RÍOS',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C115',num:'115',name:'JUAN FERNANDO QUINTERO',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C116',num:'116',name:'JHON ARIAS',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C117',num:'117',name:'LUIS SUÁREZ',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C118',num:'118',name:'IVAN PERIŠIĆ',team:'Croatia',cc:'CRO',type:'HERO'},
{id:'C119',num:'119',name:'TEAM CREST',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C120',num:'120',name:'LUKA MODRIĆ',team:'Croatia',cc:'CRO',type:'ICON'},
{id:'C121',num:'121',name:'DOMINIK LIVAKOVIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C122',num:'122',name:'DUJE ĆALETA-CAR',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C123',num:'123',name:'JOŠKO GVARDIOL',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C124',num:'124',name:'JOSIP STANIŠIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C125',num:'125',name:'MATEO KOVAČIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C126',num:'126',name:'LOVRO MAJER',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C127',num:'127',name:'MARIO PAŠALIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C128',num:'128',name:'ANTE BUDIMIR',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C129',num:'129',name:'ANDREJ KRAMARIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C130',num:'130',name:'JURIËN GAARI',team:'Curaçao',cc:'CUW',type:'HERO'},
{id:'C131',num:'131',name:'TEAM CREST',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C132',num:'132',name:'LEANDRO BACUNA',team:'Curaçao',cc:'CUW',type:'ICON'},
{id:'C133',num:'133',name:'ELOY ROOM',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C134',num:'134',name:'SHEREL FLORANUS',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C135',num:'135',name:'ROSHON VAN EIJMA',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C136',num:'136',name:'ARMANDO OBISPO',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C137',num:'137',name:'LIVANO COMENENCIA',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C138',num:'138',name:'JUNINHO BACUNA',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C139',num:'139',name:'KENJI GORRÉ',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C140',num:'140',name:'SONTJE HANSEN',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C141',num:'141',name:'JEARL MARGARITHA',team:'Curaçao',cc:'CUW',type:'BASE'},
{id:'C142',num:'142',name:'MOISÉS CAICEDO',team:'Ecuador',cc:'ECU',type:'HERO'},
{id:'C143',num:'143',name:'TEAM CREST',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C144',num:'144',name:'ENNER VALENCIA',team:'Ecuador',cc:'ECU',type:'ICON'},
{id:'C145',num:'145',name:'HERNÁN GALÍNDEZ',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C146',num:'146',name:'PIERO HINCAPIÉ',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C147',num:'147',name:'PERVIS ESTUPIÑÁN',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C148',num:'148',name:'WILLIAN PACHO',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C149',num:'149',name:'ÁNGELO PRECIADO',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C150',num:'150',name:'JOEL ORDÓÑEZ',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C151',num:'151',name:'ALAN FRANCO',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C152',num:'152',name:'GONZALO PLATA',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C153',num:'153',name:'KEVIN RODRÍGUEZ',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C154',num:'154',name:'OMAR MARMOUSH',team:'Egypt',cc:'EGY',type:'HERO'},
{id:'C155',num:'155',name:'TEAM CREST',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C156',num:'156',name:'MOHAMED SALAH',team:'Egypt',cc:'EGY',type:'ICON'},
{id:'C157',num:'157',name:'MOHAMED EL SHENAWY',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C158',num:'158',name:'MOHAMED HANY',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C159',num:'159',name:'MOHAMED ABDELMONEM',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C160',num:'160',name:'RAMY RABIA',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C161',num:'161',name:'MARWAN ATTIA',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C162',num:'162',name:'ZIZO',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C163',num:'163',name:'HAMDY FATHY',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C164',num:'164',name:'MOSTAFA MOHAMED',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C165',num:'165',name:'TRÉZÉGUET',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C166',num:'166',name:'JUDE BELLINGHAM',team:'England',cc:'ENG',type:'HERO'},
{id:'C167',num:'167',name:'TEAM CREST',team:'England',cc:'ENG',type:'BASE'},
{id:'C168',num:'168',name:'HARRY KANE',team:'England',cc:'ENG',type:'ICON'},
{id:'C169',num:'169',name:'JORDAN PICKFORD',team:'England',cc:'ENG',type:'BASE'},
{id:'C170',num:'170',name:'REECE JAMES',team:'England',cc:'ENG',type:'BASE'},
{id:'C171',num:'171',name:'JOHN STONES',team:'England',cc:'ENG',type:'BASE'},
{id:'C172',num:'172',name:'DECLAN RICE',team:'England',cc:'ENG',type:'BASE'},
{id:'C173',num:'173',name:'JORDAN HENDERSON',team:'England',cc:'ENG',type:'BASE'},
{id:'C174',num:'174',name:'PHIL FODEN',team:'England',cc:'ENG',type:'BASE'},
{id:'C175',num:'175',name:'BUKAYO SAKA',team:'England',cc:'ENG',type:'BASE'},
{id:'C176',num:'176',name:'COLE PALMER',team:'England',cc:'ENG',type:'BASE'},
{id:'C177',num:'177',name:'MARCUS RASHFORD',team:'England',cc:'ENG',type:'BASE'},
{id:'C178',num:'178',name:'OUSMANE DEMBÉLÉ',team:'France',cc:'FRA',type:'HERO'},
{id:'C179',num:'179',name:'TEAM CREST',team:'France',cc:'FRA',type:'BASE'},
{id:'C180',num:'180',name:'KYLIAN MBAPPÉ',team:'France',cc:'FRA',type:'ICON'},
{id:'C181',num:'181',name:'MIKE MAIGNAN',team:'France',cc:'FRA',type:'BASE'},
{id:'C182',num:'182',name:'WILLIAM SALIBA',team:'France',cc:'FRA',type:'BASE'},
{id:'C183',num:'183',name:'JULES KOUNDÉ',team:'France',cc:'FRA',type:'BASE'},
{id:'C184',num:'184',name:'THÉO HERNÁNDEZ',team:'France',cc:'FRA',type:'BASE'},
{id:'C185',num:'185',name:'AURÉLIEN TCHOUAMÉNI',team:'France',cc:'FRA',type:'BASE'},
{id:'C186',num:'186',name:'EDUARDO CAMAVINGA',team:'France',cc:'FRA',type:'BASE'},
{id:'C187',num:'187',name:'BRADLEY BARCOLA',team:'France',cc:'FRA',type:'BASE'},
{id:'C188',num:'188',name:'MARCUS THURAM',team:'France',cc:'FRA',type:'BASE'},
{id:'C189',num:'189',name:'RANDAL KOLO MUANI',team:'France',cc:'FRA',type:'BASE'},
{id:'C190',num:'190',name:'JAMAL MUSIALA',team:'Germany',cc:'GER',type:'HERO'},
{id:'C191',num:'191',name:'TEAM CREST',team:'Germany',cc:'GER',type:'BASE'},
{id:'C192',num:'192',name:'JOSHUA KIMMICH',team:'Germany',cc:'GER',type:'ICON'},
{id:'C193',num:'193',name:'MARC-ANDRÉ TER STEGEN',team:'Germany',cc:'GER',type:'BASE'},
{id:'C194',num:'194',name:'ANTONIO RÜDIGER',team:'Germany',cc:'GER',type:'BASE'},
{id:'C195',num:'195',name:'JONATHAN TAH',team:'Germany',cc:'GER',type:'BASE'},
{id:'C196',num:'196',name:'FELIX NMECHA',team:'Germany',cc:'GER',type:'BASE'},
{id:'C197',num:'197',name:'LEON GORETZKA',team:'Germany',cc:'GER',type:'BASE'},
{id:'C198',num:'198',name:'FLORIAN WIRTZ',team:'Germany',cc:'GER',type:'BASE'},
{id:'C199',num:'199',name:'SERGE GNABRY',team:'Germany',cc:'GER',type:'BASE'},
{id:'C200',num:'200',name:'KAI HAVERTZ',team:'Germany',cc:'GER',type:'BASE'},
{id:'C201',num:'201',name:'LEROY SANÉ',team:'Germany',cc:'GER',type:'BASE'},
{id:'C202',num:'202',name:'THOMAS PARTEY',team:'Ghana',cc:'GHA',type:'HERO'},
{id:'C203',num:'203',name:'TEAM CREST',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C204',num:'204',name:'MOHAMMED KUDUS',team:'Ghana',cc:'GHA',type:'ICON'},
{id:'C205',num:'205',name:'LAWRENCE ATI ZIGI',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C206',num:'206',name:'ALIDU SEIDU',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C207',num:'207',name:'ALEXANDER DJIKU',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C208',num:'208',name:'GIDEON MENSAH',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C209',num:'209',name:'CALEB VIRENKYI',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C210',num:'210',name:'ABDUL ISSAHAKU FATAWU',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C211',num:'211',name:'KAMALDEEN SULEMANA',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C212',num:'212',name:'JORDAN AYEW',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C213',num:'213',name:'ANTOINE SEMENYO',team:'Ghana',cc:'GHA',type:'BASE'},
{id:'C214',num:'214',name:'FRANTZDY PIERROT',team:'Haiti',cc:'HAI',type:'HERO'},
{id:'C215',num:'215',name:'TEAM CREST',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C216',num:'216',name:'DUCKENS NAZON',team:'Haiti',cc:'HAI',type:'ICON'},
{id:'C217',num:'217',name:'JOHNY PLACIDE',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C218',num:'218',name:'RICARDO ADÉ',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C219',num:'219',name:'CARLENS ARCUS',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C220',num:'220',name:'HANNES DELCROIX',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C221',num:'221',name:'LEVERTON PIERRE',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C222',num:'222',name:'DANLEY JEAN JACQUES',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C223',num:'223',name:'JEAN-RICNER BELLEGARDE',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C224',num:'224',name:'RUBEN PROVIDENCE',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C225',num:'225',name:'DON DEEDSON LOUICIUS',team:'Haiti',cc:'HAI',type:'BASE'},
{id:'C226',num:'226',name:'MEHDI TAREMI',team:'Iran',cc:'IRN',type:'HERO'},
{id:'C227',num:'227',name:'TEAM CREST',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C228',num:'228',name:'SARDAR AZMOUN',team:'Iran',cc:'IRN',type:'ICON'},
{id:'C229',num:'229',name:'ALIREZA BEIRANVAND',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C230',num:'230',name:'SHOJA KHALILZADEH',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C231',num:'231',name:'MILAD MOHAMMADI',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C232',num:'232',name:'RAMIN REZAEIAN',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C233',num:'233',name:'HOSSEIN KANAANI',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C234',num:'234',name:'SAEID EZATOLAHI',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C235',num:'235',name:'SAMAN GHODDOS',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C236',num:'236',name:'MOHAMMAD MOHEBI',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C237',num:'237',name:'ALIREZA JAHANBAKHSH',team:'Iran',cc:'IRN',type:'BASE'},
{id:'C238',num:'238',name:'FRANCK KESSIÉ',team:'Ivory Coast',cc:'CIV',type:'HERO'},
{id:'C239',num:'239',name:'TEAM CREST',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C240',num:'240',name:'SÉBASTIEN HALLER',team:'Ivory Coast',cc:'CIV',type:'ICON'},
{id:'C241',num:'241',name:'YAHIA FOFANA',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C242',num:'242',name:'GHISLAIN KONAN',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C243',num:'243',name:'ODILON KOSSOUNOU',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C244',num:'244',name:'EVAN N\'DICKA',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C245',num:'245',name:'WILFRIED SINGO',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C246',num:'246',name:'IBRAHIM SANGARÉ',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C247',num:'247',name:'NICOLAS PÉPÉ',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C248',num:'248',name:'SIMON ADINGRA',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C249',num:'249',name:'OUMAR DIAKITÉ',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C250',num:'250',name:'TAKUMI MINAMINO',team:'Japan',cc:'JPN',type:'HERO'},
{id:'C251',num:'251',name:'TEAM CREST',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C252',num:'252',name:'TAKEFUSA KUBO',team:'Japan',cc:'JPN',type:'ICON'},
{id:'C253',num:'253',name:'ZION SUZUKI',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C254',num:'254',name:'TSUYOSHI WATANABE',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C255',num:'255',name:'KAISHU SANO',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C256',num:'256',name:'AO TANAKA',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C257',num:'257',name:'DAICHI KAMADA',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C258',num:'258',name:'RITSU DOAN',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C259',num:'259',name:'KEITO NAKAMURA',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C260',num:'260',name:'SHUTO MACHINO',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C261',num:'261',name:'AYASE UEDA',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C262',num:'262',name:'YAZAN AL-NAIMAT',team:'Jordan',cc:'JOR',type:'HERO'},
{id:'C263',num:'263',name:'TEAM CREST',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C264',num:'264',name:'MUSA AL-TAAMARI',team:'Jordan',cc:'JOR',type:'ICON'},
{id:'C265',num:'265',name:'YAZEED ABULAILA',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C266',num:'266',name:'MOHAMMAD ABU HASHISH',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C267',num:'267',name:'YAZAN AL-ARAB',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C268',num:'268',name:'ABDALLAH NASIB',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C269',num:'269',name:'IBRAHIM SAADEH',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C270',num:'270',name:'NIZAR AL-RASHDAN',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C271',num:'271',name:'NOOR AL-RAWABDEH',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C272',num:'272',name:'MAHMOUD AL-MARDI',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C273',num:'273',name:'ALI OLWAN',team:'Jordan',cc:'JOR',type:'BASE'},
{id:'C274',num:'274',name:'MINJAE KIM',team:'Korea Republic',cc:'KOR',type:'HERO'},
{id:'C275',num:'275',name:'TEAM CREST',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C276',num:'276',name:'HEUNGMIN SON',team:'Korea Republic',cc:'KOR',type:'ICON'},
{id:'C277',num:'277',name:'HYEONWOO JO',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C278',num:'278',name:'YOUNGWOO SEOL',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C279',num:'279',name:'YUMIN CHO',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C280',num:'280',name:'TAESEOK LEE',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C281',num:'281',name:'INBEOM HWANG',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C282',num:'282',name:'JAESUNG LEE',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C283',num:'283',name:'KANGIN LEE',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C284',num:'284',name:'HYEONGYU OH',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C285',num:'285',name:'HEECHAN HWANG',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C286',num:'286',name:'EDSON ÁLVAREZ',team:'Mexico',cc:'MEX',type:'HERO'},
{id:'C287',num:'287',name:'TEAM CREST',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C288',num:'288',name:'RAÚL JIMÉNEZ',team:'Mexico',cc:'MEX',type:'ICON'},
{id:'C289',num:'289',name:'LUIS MALAGÓN',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C290',num:'290',name:'ISRAEL REYES',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C291',num:'291',name:'JOHAN VÁSQUEZ',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C292',num:'292',name:'CÉSAR MONTES',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C293',num:'293',name:'JESÚS GALLARDO',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C294',num:'294',name:'CARLOS RODRÍGUEZ',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C295',num:'295',name:'ORBELÍN PINEDA',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C296',num:'296',name:'HIRVING LOZANO',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C297',num:'297',name:'SANTIAGO GIMÉNEZ',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C298',num:'298',name:'YOUSSEF EN-NESYRI',team:'Morocco',cc:'MAR',type:'HERO'},
{id:'C299',num:'299',name:'TEAM CREST',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C300',num:'300',name:'ACHRAF HAKIMI',team:'Morocco',cc:'MAR',type:'ICON'},
{id:'C301',num:'301',name:'YASSINE BOUNOU',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C302',num:'302',name:'NOUSSAIR MAZRAOUI',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C303',num:'303',name:'NAYEF AGUERD',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C304',num:'304',name:'SOFYAN AMRABAT',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C305',num:'305',name:'ELIESSE BEN SEGHIR',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C306',num:'306',name:'ISMAEL SAIBARI',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C307',num:'307',name:'BRAHIM DÍAZ',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C308',num:'308',name:'ABDE EZZALZOULI',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C309',num:'309',name:'AYOUB EL KAABI',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C310',num:'310',name:'MEMPHIS DEPAY',team:'Netherlands',cc:'NED',type:'HERO'},
{id:'C311',num:'311',name:'TEAM CREST',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C312',num:'312',name:'VIRGIL VAN DIJK',team:'Netherlands',cc:'NED',type:'ICON'},
{id:'C313',num:'313',name:'BART VERBRUGGEN',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C314',num:'314',name:'NATHAN AKÉ',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C315',num:'315',name:'JEREMIE FRIMPONG',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C316',num:'316',name:'DENZEL DUMFRIES',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C317',num:'317',name:'TIJJANI REIJNDERS',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C318',num:'318',name:'RYAN GRAVENBERCH',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C319',num:'319',name:'CODY GAKPO',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C320',num:'320',name:'DONYELL MALEN',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C321',num:'321',name:'WOUT WEGHORST',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C322',num:'322',name:'MARKO STAMENIC',team:'New Zealand',cc:'NZL',type:'HERO'},
{id:'C323',num:'323',name:'TEAM CREST',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C324',num:'324',name:'CHRIS WOOD',team:'New Zealand',cc:'NZL',type:'ICON'},
{id:'C325',num:'325',name:'MAX CROCOMBE',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C326',num:'326',name:'MICHAEL BOXALL',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C327',num:'327',name:'LIBERATO CACACE',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C328',num:'328',name:'TIM PAYNE',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C329',num:'329',name:'FINN SURMAN',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C330',num:'330',name:'JOE BELL',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C331',num:'331',name:'SARPREET SINGH',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C332',num:'332',name:'MATT GARBETT',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C333',num:'333',name:'ELIJAH JUST',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C334',num:'334',name:'MARTIN ØDEGAARD',team:'Norway',cc:'NOR',type:'HERO'},
{id:'C335',num:'335',name:'TEAM CREST',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C336',num:'336',name:'ERLING HAALAND',team:'Norway',cc:'NOR',type:'ICON'},
{id:'C337',num:'337',name:'ØRJAN NYLAND',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C338',num:'338',name:'JULIAN RYERSON',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C339',num:'339',name:'KRISTOFFER VASSBAKK AJER',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C340',num:'340',name:'DAVID MØLLER WOLFE',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C341',num:'341',name:'SANDER BERGE',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C342',num:'342',name:'PATRICK BERG',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C343',num:'343',name:'ANTONIO NUSA',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C344',num:'344',name:'OSCAR BOBB',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C345',num:'345',name:'ALEXANDER SØRLOTH',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C346',num:'346',name:'MICHAEL AMIR MURILLO',team:'Panama',cc:'PAN',type:'HERO'},
{id:'C347',num:'347',name:'TEAM CREST',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C348',num:'348',name:'ANÍBAL GODOY',team:'Panama',cc:'PAN',type:'ICON'},
{id:'C349',num:'349',name:'ORLANDO MOSQUERA',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C350',num:'350',name:'ANDRÉS ANDRADE',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C351',num:'351',name:'FIDEL ESCOBAR',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C352',num:'352',name:'CRISTIAN MARTÍNEZ',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C353',num:'353',name:'ADALBERTO CARRASQUILLA',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C354',num:'354',name:'ÉDGAR BÁRCENAS',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C355',num:'355',name:'JOSÉ FAJARDO',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C356',num:'356',name:'ISMAEL DÍAZ',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C357',num:'357',name:'JOSÉ LUIZ RODRÍGUEZ',team:'Panama',cc:'PAN',type:'BASE'},
{id:'C358',num:'358',name:'GUSTAVO GÓMEZ',team:'Paraguay',cc:'PAR',type:'HERO'},
{id:'C359',num:'359',name:'TEAM CREST',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C360',num:'360',name:'MIGUEL ALMIRÓN',team:'Paraguay',cc:'PAR',type:'ICON'},
{id:'C361',num:'361',name:'ROBERTO FERNÁNDEZ',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C362',num:'362',name:'JUAN JOSÉ CÁCERES',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C363',num:'363',name:'OMAR ALDERETE',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C364',num:'364',name:'JÚNIOR ALONSO',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C365',num:'365',name:'ANDRÉS CUBAS',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C366',num:'366',name:'MATHÍAS VILLASANTI',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C367',num:'367',name:'JULIO ENCISO',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C368',num:'368',name:'RAMÓN SOSA',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C369',num:'369',name:'ANTONIO SANABRIA',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C370',num:'370',name:'VITINHA',team:'Portugal',cc:'POR',type:'HERO'},
{id:'C371',num:'371',name:'TEAM CREST',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C372',num:'372',name:'CRISTIANO RONALDO',team:'Portugal',cc:'POR',type:'ICON'},
{id:'C373',num:'373',name:'DIOGO COSTA',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C374',num:'374',name:'RÚBEN DIAS',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C375',num:'375',name:'NUNO MENDES',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C376',num:'376',name:'BERNARDO SILVA',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C377',num:'377',name:'BRUNO FERNANDES',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C378',num:'378',name:'RÚBEN NEVES',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C379',num:'379',name:'FRANCISCO CONCEIÇÃO',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C380',num:'380',name:'PEDRO NETO',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C381',num:'381',name:'RAFAEL LEÃO',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C382',num:'382',name:'ALMOEZ ALI',team:'Qatar',cc:'QAT',type:'HERO'},
{id:'C383',num:'383',name:'TEAM CREST',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C384',num:'384',name:'HASAN AL-HAYDOS',team:'Qatar',cc:'QAT',type:'ICON'},
{id:'C385',num:'385',name:'MESHAAL BARSHAM',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C386',num:'386',name:'BOUALEM KHOUKHI',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C387',num:'387',name:'LUCAS MENDES',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C388',num:'388',name:'PEDRO MIGUEL',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C389',num:'389',name:'HOMAM AL-AMIN',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C390',num:'390',name:'AHMED FATHI',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C391',num:'391',name:'EDMÍLSON JUNIOR',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C392',num:'392',name:'AHMED AL-GANEHI',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C393',num:'393',name:'AKRAM HASSAN AFIF',team:'Qatar',cc:'QAT',type:'BASE'},
{id:'C394',num:'394',name:'FERAS ALBRIKAN',team:'Saudi Arabia',cc:'KSA',type:'HERO'},
{id:'C395',num:'395',name:'TEAM CREST',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C396',num:'396',name:'SALEM ALDAWSARI',team:'Saudi Arabia',cc:'KSA',type:'ICON'},
{id:'C397',num:'397',name:'NAWAF ALAQIDI',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C398',num:'398',name:'HASSAN ALTAMBAKTI',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C399',num:'399',name:'JEHAD THIKRI',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C400',num:'400',name:'SAUD ABDULHAMID',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C401',num:'401',name:'NASSER ALDAWSARI',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C402',num:'402',name:'ABDULLAH ALKHAIBARI',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C403',num:'403',name:'MUSAB ALJUWAYR',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C404',num:'404',name:'SALEH ABU ALSHAMAT',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C405',num:'405',name:'SALEH ALSHEHRI',team:'Saudi Arabia',cc:'KSA',type:'BASE'},
{id:'C406',num:'406',name:'SCOTT MCTOMINAY',team:'Scotland',cc:'SCO',type:'HERO'},
{id:'C407',num:'407',name:'TEAM CREST',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C408',num:'408',name:'ANDREW ROBERTSON',team:'Scotland',cc:'SCO',type:'ICON'},
{id:'C409',num:'409',name:'ANGUS GUNN',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C410',num:'410',name:'KIERAN TIERNEY',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C411',num:'411',name:'GRANT HANLEY',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C412',num:'412',name:'BILLY GILMOUR',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C413',num:'413',name:'LEWIS FERGUSON',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C414',num:'414',name:'RYAN CHRISTIE',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C415',num:'415',name:'JOHN MCGINN',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C416',num:'416',name:'BEN GANNON-DOAK',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C417',num:'417',name:'CHÉ ADAMS',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C418',num:'418',name:'KALIDOU KOULIBALY',team:'Senegal',cc:'SEN',type:'HERO'},
{id:'C419',num:'419',name:'TEAM CREST',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C420',num:'420',name:'SADIO MANÉ',team:'Senegal',cc:'SEN',type:'ICON'},
{id:'C421',num:'421',name:'EDOUARD MENDY',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C422',num:'422',name:'MOUSSA NIAKHATÉ',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C423',num:'423',name:'EL HADJI MALICK DIOUF',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C424',num:'424',name:'IDRISSA GANA GUEYE',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C425',num:'425',name:'PAPE MATAR SARR',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C426',num:'426',name:'ILIMAN NDIAYE',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C427',num:'427',name:'KRÉPIN DIATTA',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C428',num:'428',name:'ISMAÏLA SARR',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C429',num:'429',name:'NICOLAS JACKSON',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C430',num:'430',name:'LYLE FOSTER',team:'South Africa',cc:'RSA',type:'HERO'},
{id:'C431',num:'431',name:'TEAM CREST',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C432',num:'432',name:'RONWEN WILLIAMS',team:'South Africa',cc:'RSA',type:'ICON'},
{id:'C433',num:'433',name:'SIYABONGA NGEZANA',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C434',num:'434',name:'AUBREY MODIBA',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C435',num:'435',name:'MBEKEZELI MBOKAZI',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C436',num:'436',name:'KHULISO MUDAU',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C437',num:'437',name:'TEBOHO MOKOENA',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C438',num:'438',name:'VAYA SITHOLE',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C439',num:'439',name:'THEMBA ZWANE',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C440',num:'440',name:'OSWIN APPOLLIS',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C441',num:'441',name:'IQRAAM RAYNERS',team:'South Africa',cc:'RSA',type:'BASE'},
{id:'C442',num:'442',name:'LAMINE YAMAL',team:'Spain',cc:'ESP',type:'HERO'},
{id:'C443',num:'443',name:'TEAM CREST',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C444',num:'444',name:'RODRI',team:'Spain',cc:'ESP',type:'ICON'},
{id:'C445',num:'445',name:'UNAI SIMÓN',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C446',num:'446',name:'ROBIN LE NORMAND',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C447',num:'447',name:'DEAN HUIJSEN',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C448',num:'448',name:'MARC CUCURELLA',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C449',num:'449',name:'MARTÍN ZUBIMENDI',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C450',num:'450',name:'PEDRI',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C451',num:'451',name:'FABIÁN RUIZ',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C452',num:'452',name:'NICO WILLIAMS',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C453',num:'453',name:'MIKEL OYARZABAL',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C454',num:'454',name:'MANUEL AKANJI',team:'Switzerland',cc:'SUI',type:'HERO'},
{id:'C455',num:'455',name:'TEAM CREST',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C456',num:'456',name:'GRANIT XHAKA',team:'Switzerland',cc:'SUI',type:'ICON'},
{id:'C457',num:'457',name:'GREGOR KOBEL',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C458',num:'458',name:'NICO ELVEDI',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C459',num:'459',name:'RICARDO RODRÍGUEZ',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C460',num:'460',name:'SILVAN WIDMER',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C461',num:'461',name:'DENIS ZAKARIA',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C462',num:'462',name:'REMO FREULER',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C463',num:'463',name:'BREEL EMBOLO',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C464',num:'464',name:'RUBÉN VARGAS',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C465',num:'465',name:'DAN NDOYE',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C466',num:'466',name:'FERJANI SASSI',team:'Tunisia',cc:'TUN',type:'HERO'},
{id:'C467',num:'467',name:'TEAM CREST',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C468',num:'468',name:'ELLYES SKHIRI',team:'Tunisia',cc:'TUN',type:'ICON'},
{id:'C469',num:'469',name:'AYMEN DAHMEN',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C470',num:'470',name:'MONTASSAR TALBI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C471',num:'471',name:'YASSINE MERIAH',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C472',num:'472',name:'ALI ABDI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C473',num:'473',name:'AÏSSA LAÏDOUNI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C474',num:'474',name:'HANNIBAL MEJBRI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C475',num:'475',name:'NAÏM SLITI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C476',num:'476',name:'ELIAS ACHOURI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C477',num:'477',name:'HAZEM MASTOURI',team:'Tunisia',cc:'TUN',type:'BASE'},
{id:'C478',num:'478',name:'WESTON MCKENNIE',team:'United States',cc:'USA',type:'HERO'},
{id:'C479',num:'479',name:'TEAM CREST',team:'United States',cc:'USA',type:'BASE'},
{id:'C480',num:'480',name:'CHRISTIAN PULISIC',team:'United States',cc:'USA',type:'ICON'},
{id:'C481',num:'481',name:'MATT FREESE',team:'United States',cc:'USA',type:'BASE'},
{id:'C482',num:'482',name:'CHRIS RICHARDS',team:'United States',cc:'USA',type:'BASE'},
{id:'C483',num:'483',name:'TIM REAM',team:'United States',cc:'USA',type:'BASE'},
{id:'C484',num:'484',name:'ANTONEE ROBINSON',team:'United States',cc:'USA',type:'BASE'},
{id:'C485',num:'485',name:'TANNER TESSMANN',team:'United States',cc:'USA',type:'BASE'},
{id:'C486',num:'486',name:'TYLER ADAMS',team:'United States',cc:'USA',type:'BASE'},
{id:'C487',num:'487',name:'TIMOTHY WEAH',team:'United States',cc:'USA',type:'BASE'},
{id:'C488',num:'488',name:'MALIK TILLMAN',team:'United States',cc:'USA',type:'BASE'},
{id:'C489',num:'489',name:'FOLARIN BALOGUN',team:'United States',cc:'USA',type:'BASE'},
{id:'C490',num:'490',name:'JOSÉ MARÍA GIMÉNEZ',team:'Uruguay',cc:'URU',type:'HERO'},
{id:'C491',num:'491',name:'TEAM CREST',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C492',num:'492',name:'FEDERICO VALVERDE',team:'Uruguay',cc:'URU',type:'ICON'},
{id:'C493',num:'493',name:'SERGIO ROCHET',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C494',num:'494',name:'RONALD ARAÚJO',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C495',num:'495',name:'SEBASTIÁN CÁCERES',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C496',num:'496',name:'MATHÍAS OLIVERA',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C497',num:'497',name:'NAHITAN NÁNDEZ',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C498',num:'498',name:'RODRIGO BENTANCUR',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C499',num:'499',name:'MANUEL UGARTE',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C500',num:'500',name:'FACUNDO PELLISTRI',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C501',num:'501',name:'DARWIN NÚÑEZ',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C502',num:'502',name:'ABDUKODIR KHUSANOV',team:'Uzbekistan',cc:'UZB',type:'HERO'},
{id:'C503',num:'503',name:'TEAM CREST',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C504',num:'504',name:'ELDOR SHOMURODOV',team:'Uzbekistan',cc:'UZB',type:'ICON'},
{id:'C505',num:'505',name:'UTKIR YUSUPOV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C506',num:'506',name:'FARRUKH SAYFIEV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C507',num:'507',name:'SHERZOD NASRULLAEV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C508',num:'508',name:'HUSNIDDIN ALIQULOV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C509',num:'509',name:'RUSTAM ASHURMATOV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C510',num:'510',name:'KHOJIAKBAR ALIJONOV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C511',num:'511',name:'ODILJON HAMROBEKOV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C512',num:'512',name:'OTABEK SHUKUROV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C513',num:'513',name:'ABBOSBEK FAYZULLAEV',team:'Uzbekistan',cc:'UZB',type:'BASE'},
{id:'C514',num:'514',name:'NCL/JAM - RCD',team:'Contenders',cc:'CONT',type:'BASE'},
{id:'C515',num:'515',name:'SUR/BOL - IRQ',team:'Contenders',cc:'CONT',type:'BASE'},
{id:'C516',num:'516',name:'ITA - NIR/WAL - BIH',team:'Contenders',cc:'CONT',type:'BASE'},
{id:'C517',num:'517',name:'UKR - SWE/POL - ALB',team:'Contenders',cc:'CONT',type:'BASE'},
{id:'C518',num:'518',name:'TUR - ROU/SVK - KOS',team:'Contenders',cc:'CONT',type:'BASE'},
{id:'C519',num:'519',name:'DEN - MKD/CZE - IRL',team:'Contenders',cc:'CONT',type:'BASE'},
{id:'C520',num:'520',name:'HJULMAND',team:'Denmark',cc:'DEN',type:'BASE'},
{id:'C521',num:'521',name:'HØJBJERG',team:'Denmark',cc:'DEN',type:'BASE'},
{id:'C522',num:'522',name:'ERIKSEN',team:'Denmark',cc:'DEN',type:'BASE'},
{id:'C523',num:'523',name:'DAMSGAARD',team:'Denmark',cc:'DEN',type:'BASE'},
{id:'C524',num:'524',name:'HØJLUND',team:'Denmark',cc:'DEN',type:'BASE'},
{id:'C525',num:'525',name:'DONNARUMMA',team:'Italy',cc:'ITA',type:'BASE'},
{id:'C526',num:'526',name:'BASTONI',team:'Italy',cc:'ITA',type:'BASE'},
{id:'C527',num:'527',name:'TONALI',team:'Italy',cc:'ITA',type:'BASE'},
{id:'C528',num:'528',name:'BARELLA',team:'Italy',cc:'ITA',type:'BASE'},
{id:'C529',num:'529',name:'KEAN',team:'Italy',cc:'ITA',type:'BASE'},
{id:'C530',num:'530',name:'BLAKE',team:'Jamaica',cc:'JAM',type:'BASE'},
{id:'C531',num:'531',name:'PINNOCK',team:'Jamaica',cc:'JAM',type:'BASE'},
{id:'C532',num:'532',name:'GRAY',team:'Jamaica',cc:'JAM',type:'BASE'},
{id:'C533',num:'533',name:'BAILEY',team:'Jamaica',cc:'JAM',type:'BASE'},
{id:'C534',num:'534',name:'NICHOLSON',team:'Jamaica',cc:'JAM',type:'BASE'},
{id:'C535',num:'535',name:'CASH',team:'Poland',cc:'POL',type:'BASE'},
{id:'C536',num:'536',name:'KIWIOR',team:'Poland',cc:'POL',type:'BASE'},
{id:'C537',num:'537',name:'ZIELIŃSKI',team:'Poland',cc:'POL',type:'BASE'},
{id:'C538',num:'538',name:'SZYMAŃSKI',team:'Poland',cc:'POL',type:'BASE'},
{id:'C539',num:'539',name:'LEWANDOWSKI',team:'Poland',cc:'POL',type:'BASE'},
{id:'C540',num:'540',name:'HIEN',team:'Sweden',cc:'SWE',type:'BASE'},
{id:'C541',num:'541',name:'KULUSEVSKI',team:'Sweden',cc:'SWE',type:'BASE'},
{id:'C542',num:'542',name:'ELANGA',team:'Sweden',cc:'SWE',type:'BASE'},
{id:'C543',num:'543',name:'GYÖKERES',team:'Sweden',cc:'SWE',type:'BASE'},
{id:'C544',num:'544',name:'ISAK',team:'Sweden',cc:'SWE',type:'BASE'},
{id:'C545',num:'545',name:'SÖYÜNCÜ',team:'Turkey',cc:'TUR',type:'BASE'},
{id:'C546',num:'546',name:'ÇALHANOĞLU',team:'Turkey',cc:'TUR',type:'BASE'},
{id:'C547',num:'547',name:'GÜLER',team:'Turkey',cc:'TUR',type:'BASE'},
{id:'C548',num:'548',name:'YILDIZ',team:'Turkey',cc:'TUR',type:'BASE'},
{id:'C549',num:'549',name:'AKTÜRKOĞLU',team:'Turkey',cc:'TUR',type:'BASE'},
{id:'C550',num:'550',name:'MARTÍNEZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C551',num:'551',name:'COURTOIS',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C552',num:'552',name:'ALISSON',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C553',num:'553',name:'MAIGNAN',team:'France',cc:'FRA',type:'BASE'},
{id:'C554',num:'554',name:'SUZUKI',team:'Japan',cc:'JPN',type:'BASE'},
{id:'C555',num:'555',name:'BOUNOU',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C556',num:'556',name:'DIOGO COSTA',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C557',num:'557',name:'SIMÓN',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C558',num:'558',name:'KOBEL',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C559',num:'559',name:'ÉDER MILITÃO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C560',num:'560',name:'DAVIES',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C561',num:'561',name:'SALIBA',team:'France',cc:'FRA',type:'BASE'},
{id:'C562',num:'562',name:'RÜDIGER',team:'Germany',cc:'GER',type:'BASE'},
{id:'C563',num:'563',name:'KIM',team:'Korea Republic',cc:'KOR',type:'BASE'},
{id:'C564',num:'564',name:'HAKIMI',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C565',num:'565',name:'VAN DIJK',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C566',num:'566',name:'NUNO MENDES',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C567',num:'567',name:'HUIJSEN',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C568',num:'568',name:'ENZO FERNÁNDEZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C569',num:'569',name:'DE BRUYNE',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C570',num:'570',name:'CASEMIRO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C571',num:'571',name:'MODRIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C572',num:'572',name:'CAICEDO',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C573',num:'573',name:'BELLINGHAM',team:'England',cc:'ENG',type:'BASE'},
{id:'C574',num:'574',name:'TCHOUAMÉNI',team:'France',cc:'FRA',type:'BASE'},
{id:'C575',num:'575',name:'WIRTZ',team:'Germany',cc:'GER',type:'BASE'},
{id:'C576',num:'576',name:'AMRABAT',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C577',num:'577',name:'REIJNDERS',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C578',num:'578',name:'ØDEGAARD',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C579',num:'579',name:'VITINHA',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C580',num:'580',name:'MCTOMINAY',team:'Scotland',cc:'SCO',type:'BASE'},
{id:'C581',num:'581',name:'RODRI',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C582',num:'582',name:'PEDRI',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C583',num:'583',name:'XHAKA',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C584',num:'584',name:'TYLER ADAMS',team:'United States',cc:'USA',type:'BASE'},
{id:'C585',num:'585',name:'VALVERDE',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C586',num:'586',name:'ÁLVAREZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C587',num:'587',name:'LUKAKU',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C588',num:'588',name:'RAPHINHA',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C589',num:'589',name:'DAVID',team:'Canada',cc:'CAN',type:'BASE'},
{id:'C590',num:'590',name:'DÍAZ',team:'Colombia',cc:'COL',type:'BASE'},
{id:'C591',num:'591',name:'KRAMARIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C592',num:'592',name:'VALENCIA',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C593',num:'593',name:'MARMOUSH',team:'Egypt',cc:'EGY',type:'BASE'},
{id:'C594',num:'594',name:'RASHFORD',team:'England',cc:'ENG',type:'BASE'},
{id:'C595',num:'595',name:'KOLO MUANI',team:'France',cc:'FRA',type:'BASE'},
{id:'C596',num:'596',name:'HAVERTZ',team:'Germany',cc:'GER',type:'BASE'},
{id:'C597',num:'597',name:'HALLER',team:'Ivory Coast',cc:'CIV',type:'BASE'},
{id:'C598',num:'598',name:'JIMÉNEZ',team:'Mexico',cc:'MEX',type:'BASE'},
{id:'C599',num:'599',name:'EN-NESYRI',team:'Morocco',cc:'MAR',type:'BASE'},
{id:'C600',num:'600',name:'GAKPO',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C601',num:'601',name:'WOOD',team:'New Zealand',cc:'NZL',type:'BASE'},
{id:'C602',num:'602',name:'SØRLOTH',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C603',num:'603',name:'JACKSON',team:'Senegal',cc:'SEN',type:'BASE'},
{id:'C604',num:'604',name:'OYARZABAL',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C605',num:'605',name:'EMBOLO',team:'Switzerland',cc:'SUI',type:'BASE'},
{id:'C606',num:'606',name:'PULISIC',team:'United States',cc:'USA',type:'BASE'},
{id:'C607',num:'607',name:'NÚÑEZ',team:'Uruguay',cc:'URU',type:'BASE'},
{id:'C608',num:'608',name:'PAZ',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C609',num:'609',name:'MASTANTUONO',team:'Argentina',cc:'ARG',type:'BASE'},
{id:'C610',num:'610',name:'DEBAST',team:'Belgium',cc:'BEL',type:'BASE'},
{id:'C611',num:'611',name:'WESLEY',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C612',num:'612',name:'ESTÊVÃO',team:'Brazil',cc:'BRA',type:'BASE'},
{id:'C613',num:'613',name:'SUČIĆ',team:'Croatia',cc:'CRO',type:'BASE'},
{id:'C614',num:'614',name:'PÁEZ',team:'Ecuador',cc:'ECU',type:'BASE'},
{id:'C615',num:'615',name:'ROGERS',team:'England',cc:'ENG',type:'BASE'},
{id:'C616',num:'616',name:'DOUÉ',team:'France',cc:'FRA',type:'BASE'},
{id:'C617',num:'617',name:'BARCOLA',team:'France',cc:'FRA',type:'BASE'},
{id:'C618',num:'618',name:'WOLTEMADE',team:'Germany',cc:'GER',type:'BASE'},
{id:'C619',num:'619',name:'SIMONS',team:'Netherlands',cc:'NED',type:'BASE'},
{id:'C620',num:'620',name:'SCHJELDERUP',team:'Norway',cc:'NOR',type:'BASE'},
{id:'C621',num:'621',name:'GÓMEZ',team:'Paraguay',cc:'PAR',type:'BASE'},
{id:'C622',num:'622',name:'JOÃO NEVES',team:'Portugal',cc:'POR',type:'BASE'},
{id:'C623',num:'623',name:'CUBARSÍ',team:'Spain',cc:'ESP',type:'BASE'},
{id:'C624',num:'624',name:'OFFICIAL EMBLEM',team:'FIFA',cc:'FIFA',type:'BASE'},
{id:'C625',num:'625',name:'OFFICIAL MASCOT - MAPLE',team:'FIFA',cc:'FIFA',type:'BASE'},
{id:'C626',num:'626',name:'OFFICIAL MASCOT - CLUTCH',team:'FIFA',cc:'FIFA',type:'BASE'},
{id:'C627',num:'627',name:'OFFICIAL MASCOT - ZAVU',team:'FIFA',cc:'FIFA',type:'BASE'},
{id:'C628',num:'628',name:'ETERNOS 22 - DEFENDERS',team:'FIFA',cc:'FIFA',type:'BASE'},
{id:'C629',num:'629',name:'ETERNOS 22 - MIDFIELDERS',team:'FIFA',cc:'FIFA',type:'BASE'},
{id:'C630',num:'630',name:'ETERNOS 22 - FORWARDS',team:'FIFA',cc:'FIFA',type:'BASE'},
];
